version: "2"
services:
  ai-server:
    container_name: ai-server
    build:
      context: AI/
      dockerfile: Dockerfile
    environment:
      - AWS_PROFILE=test-helper
    ports:
      - 5000:5000
    volumes:
      - ~/.aws/:/root/.aws:ro