version: "2"
services:
  reverse-proxy:
    container_name: reverse-proxy-ai
    build:
      context: nginx/
      dockerfile : Dockerfile
    image: reverse-proxy-ai:latest
    ports:
      - 80:80
    depends_on:
      - ai-server

  ai-server:
    container_name: ai-server
    build:
      context: AI/
      dockerfile: Dockerfile
    environment:
      - AWS_PROFILE=test-helper
    ports:
      - 5000:5000
    volumes:
      - ~/.aws/:/root/.aws:ro